version: '3.8'

services:
  # PHP-FPM (Laravel app)
  app:
    image: php:8.0-fpm
    container_name: aisyah_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - mysql

  # Nginx Web Server
  nginx:
    image: nginx:latest
    container_name: aisyah_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: aisyah_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: aisyah_db
      MYSQL_USER: aisyah_user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
